### ISSUE TITLE
Settings: integration

### ISSUE THREAD

**Issue by katerinabc** [RnDAO/tc-uiComm#10]
# Problem
In the setting page, a user can decide to integrate another discord server. Selecting the button lets me decide a time frame and the channels, but not pick another discord server. 

# Solution
Remove the option to integrate another community (I thought this is what we decided in a call)

**Comment by Zueis** [comment]
Sorry, we haven't this part in the last version (It's finished today and I'm waiting for Behzad and Mehrdad to push their side on master) So, after that, I think you can recheck it.
