### ISSUE TITLE
Hide notification after time period or read.

### ISSUE THREAD

**Issue by cyri113** [RnDAO/tc-uiComm#106]
One more thing that I noticed: the ask for help option sends a message telling you that you can ask for help there. This results in a notification on the tab. The notification doesn't remove, even after I open the message. This is annoying because it makes me think that there is a new notification that I should look at but it's just a message telling me that I can ask for help and I've already seen that message

https://discord.com/channels/915914985140531240/1115310101222412430/1117161868935569540

**Comment by daniel-ospina** [comment]
Fixed, although we have to choose between no notification at the top at all or an annoying notification that doesn't disappear. I opted for no notification
