### ISSUE TITLE
Remove highcharts.com link

### ISSUE THREAD

**Issue by katerinabc** [RnDAO/tc-uiComm#11]
# Problem
Below the heatmap, on the button right, is a link to highcharts. com. Selecting it directs to their website. 

# Solution
Remove the link.

**Comment by katerinabc** [comment]
only if legally allowed

**Comment by Zueis** [comment]
Based on @thegadget-eth words we can't legally remove it on the free version of Highcharts.

**Comment by katerinabc** [comment]
closed as legally can't be done
