### ISSUE TITLE
 Filter heatmap by channel

### ISSUE THREAD

**Issue by mehrdadmms** [RnDAO/tc-uiComm#23]
# Goal
- As a user, I should be able to select a list of channels and see the heatmap chart based on those channels

# How
- Reach out to UI/UX to confirm design
- Implement the design
- Connect the APIs and visualize the data 

# Dependency 
https://github.com/RnDAO/tc-serverComm/issues/48

**Comment by Zueis** [comment]
We need a new API for this task.
the requirement is that we have to show a list of channels that the admin gives access to analysis and we don't have this API. So, I think @Behzad-rabiei should implement API for this section.
