### ISSUE TITLE
Fix welcome message

### ISSUE THREAD

**Issue by katerinabc** [RnDAO/tc-uiComm#5]
Fix text when the user wants to create an account. These notes refer to the page that shows after selecting "try now"

1. the welcome message says *welcome to XYZ*. Change it to *Welcome to TogetherCrew*
2. The text for the 2nd step sounds clunky. Remove *be* so that the text says *Select time period and channels you want to analyse*.

**Comment by mehrdadmms** [comment]
@katerinabc Please reach out to our UI/UX first.

**Comment by katerinabc** [comment]
point 1 & 2 has been resolved with the latest update. I'm closing the issue.
